ui:
  username: admin

longhorn:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: longhorn-ui-secret
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required "
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
