repository:
  url: https://github.com/d3adb5/argo-applications

argocd:
  namespace: argo-cd

metallb:
  namespace: metallb
  ipSharingKey: metallb-single-ip

ingress:
  namespace: ingress

certManager:
  namespace: cert-manager

longhorn:
  namespace: longhorn

prometheus:
  namespace: prometheus

minecraft:
  namespace: minecraft

vault:
  namespace: vault
