repository:
  url: https://github.com/d3adb5/argo-applications

argocd:
  namespace: argo-cd

metallb:
  namespace: metallb
  ipSharingKey: metallb-single-ip
  speaker:
    tolerations:
      - key: purpose
        operator: Equal
        value: storage
        effect: NoSchedule

ingress:
  namespace: ingress

certManager:
  namespace: cert-manager

longhorn:
  namespace: longhorn
  defaultSettings:
    taintToleration: "purpose=storage:NoSchedule"
  ingress:
    host: longhorn.d3adb5.net
    ingressClassName: nginx
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  tolerations:
    - key: purpose
      operator: Equal
      value: storage
      effect: NoSchedule

prometheus:
  namespace: prometheus

minecraft:
  namespace: minecraft

vault:
  namespace: vault

plex:
  namespace: media
  image:
    pullPolicy: Always
  config:
    storageClassName: longhorn-nvme
    storageSize: 2Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    url: plex.d3adb5.net
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  extraVolumes:
    - name: media-library
      persistentVolumeClaim:
        claimName: media-library
  extraVolumeMounts:
    - name: media-library
      mountPath: /media/tv
      subPath: tv
    - name: media-library
      mountPath: /media/movies
      subPath: movies
  extraEnv:
    # If redeploying, generate a new claim token through https://www.plex.tv/claim/
    PLEX_CLAIM: "claim-gn9iLXVVLsg11o8Zzuac"
    HOSTNAME: Plexgu
    PLEX_UID: 1000
    PLEX_GID: 1000
    TZ: America/Vancouver
