repository:
  url: https://github.com/d3adb5/argo-applications

argocd:
  namespace: argo-cd

metallb:
  namespace: metallb
  ipSharingKey: &metallb-sharing-key metallb-single-ip

ingress:
  namespace: ingress

certManager:
  namespace: cert-manager

longhorn:
  namespace: longhorn
  defaultSettings:
    taintToleration: "purpose=storage:NoSchedule"
  ingress:
    host: longhorn.d3adb5.net
    ingressClassName: nginx
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  tolerations:
    - key: purpose
      operator: Equal
      value: storage
      effect: NoSchedule

prometheus:
  namespace: prometheus

minecraft:
  namespace: minecraft

vault:
  namespace: vault

plex:
  namespace: media

transmission:
  namespace: media

sonarr:
  namespace: media
  valuesObject:
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/sonarr
      tag: latest
      pullPolicy: Always
    persistence:
      config:
        storageClass: longhorn-nvme
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi
    service:
      port: 8989
    ingress:
      enabled: true
      host: sonarr.d3adb5.net
      className: nginx
      tls:
        enabled: true
        secretName: sonarr-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    extraEnv:
      - name: TZ
        value: America/Vancouver
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
    extraVolumes:
      - name: media-library
        persistentVolumeClaim:
          claimName: media-library
    extraVolumeMounts:
      - name: media-library
        mountPath: /media
      - name: media-library
        mountPath: /downloads
        subPath: torrents

radarr:
  namespace: media
  valuesObject:
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/radarr
      tag: latest
      pullPolicy: Always
    persistence:
      config:
        storageClass: longhorn-nvme
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi
    service:
      port: 7878
    ingress:
      enabled: true
      host: radarr.d3adb5.net
      className: nginx
      tls:
        enabled: true
        secretName: radarr-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    extraEnv:
      - name: TZ
        value: America/Vancouver
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
    extraVolumes:
      - name: media-library
        persistentVolumeClaim:
          claimName: media-library
    extraVolumeMounts:
      - name: media-library
        mountPath: /media
      - name: media-library
        mountPath: /downloads
        subPath: torrents

overseerr:
  namespace: media

prowlarr:
  namespace: media
  valuesObject:
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/prowlarr
      tag: latest
      pullPolicy: Always
    persistence:
      config:
        storageClass: longhorn-nvme
    service:
      port: 9696
    ingress:
      enabled: true
      host: prowlarr.d3adb5.net
      className: nginx
      tls:
        enabled: true
        secretName: prowlarr-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    extraEnv:
      - name: TZ
        value: America/Vancouver
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
