repository:
  url: https://github.com/d3adb5/argo-applications

argocd:
  namespace: argo-cd

metallb:
  namespace: metallb
  ipSharingKey: metallb-single-ip

ingress:
  namespace: ingress

certManager:
  namespace: cert-manager

longhorn:
  namespace: longhorn
  ingress:
    host: longhorn.d3adb5.net
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  tolerations:
    - key: purpose
      operator: Equal
      value: storage
      effect: NoSchedule

prometheus:
  namespace: prometheus

minecraft:
  namespace: minecraft

vault:
  namespace: vault
