apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: keycloak
  source:
    repoURL: {{ .Values.appOfApps.repoURL }}
    targetRevision: HEAD
    path: keycloak

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.keycloak.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
