apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: storage
  source:
    repoURL: {{ .Values.repository.url }}
    targetRevision: HEAD
    path: applications/longhorn

    helm:
      valuesObject:
        longhorn:
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClassReplicaCount: 1
            migratable: true
          ingress:
            enabled: true
            ingressClassName: {{ .Values.longhorn.ingress.ingressClassName }}
            host: {{ .Values.longhorn.ingress.host }}
            annotations:
              {{- toYaml .Values.longhorn.ingress.annotations | nindent 14 }}
            tls: {{ .Values.longhorn.ingress.tls }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.longhorn.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - kind: Secret
      name: longhorn-ui-secret
      jsonPointers:
        - /data/auth
        - /data/generatedPassword
