apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media
  source:
    repoURL: {{ .Values.repository.url }}
    targetRevision: HEAD
    path: x-arr

    helm:
      valuesObject:
        {{- toYaml .Values.overseerr.valuesObject | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.overseerr.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
