apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media
  source:
    repoURL: {{ .Values.helmRepos.d3adb5 }}
    targetRevision: 1.1.0
    chart: stateful

    helm:
      valuesObject:
        replicaCount: 1
        podAnnotations:
          linkerd.io/inject: enabled
        image:
          repository: lscr.io/linuxserver/overseerr
          tag: "1.34.0@sha256:e958969abc43216ad371266c794e224a4f81cc25af0146ece314ded58520678b"
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          initialDelaySeconds: 120
        service:
          port: 5055
        ingress:
          enabled: true
          host: requests.d3adb5.net
          className: nginx
          tls:
            enabled: true
            secretName: overseerr-tls
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
        extraEnv:
          - name: TZ
            value: America/Vancouver
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        extraVolumeMounts:
          - name: config
            mountPath: /config
        extraVolumeClaimTemplates:
          - metadata:
              name: config
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: longhorn-nvme
              resources:
                requests:
                  storage: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.media.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
