apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: 0.11.0
    chart: plex-media-server

    helm:
      valuesObject:
        image:
          registry: lscr.io
          repository: linuxserver/plex
          tag: "1.41.8@sha256:7794c25926494a63da421fabf2898dd38c4d6190f9146450fc0e29da8025ed2c"
          pullPolicy: IfNotPresent
        ingress:
          enabled: true
          ingressClassName: nginx
          url: plex.d3adb5.net
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
        extraEnv:
          # If redeploying, generate a new claim token through https://www.plex.tv/claim/
          PLEX_CLAIM: "claim-XCDywQgFEjsJF8rkMSSa"
          HOSTNAME: Plex
          PUID: 1000
          PGID: 1000
          VERSION: docker
          TZ: America/Vancouver
        extraVolumes:
          - name: movies-library
            persistentVolumeClaim:
              claimName: {{ .Values.media.libraries.movies.claimName }}
          - name: tv-library
            persistentVolumeClaim:
              claimName: {{ .Values.media.libraries.tv.claimName }}
        extraVolumeMounts:
          - name: tv-library
            mountPath: /media/tv
            subPath: library
          - name: movies-library
            mountPath: /media/movies
            subPath: library
        service:
          type: NodePort
          nodePort: 32400
        pms:
          storageClassName: longhorn-nvme
          configStorage: 4Gi
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 4
              memory: 4Gi
        statefulSet:
          podAnnotations:
            linkerd.io/inject: enabled

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.media.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
