apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission-tv
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media
  source:
    repoURL: {{ .Values.helmRepos.d3adb5 }}
    targetRevision: 0.1.0
    chart: transmission

    helm:
      valuesObject:
        image:
          repository: lscr.io/linuxserver/transmission
          pullPolicy: IfNotPresent
          tag: "4.0.6@sha256:cbd1f91f9c31615057ce2744aad8589f343176b4895d13afa656d2d54dd12b66"
        podAnnotations:
          linkerd.io/inject: enabled
        replicaCount: 1
        resources:
          requests:
            cpu: 350m
            memory: 2Gi
          limits:
            cpu: 350m
            memory: 2Gi
        persistence:
          config:
            storageClass: longhorn-nvme
        ingress:
          enabled: true
          className: nginx
          host: tv.transmission.d3adb5.net
          tls:
            enabled: true
            secretName: transmission-tv-tls
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
        peerService:
          type: NodePort
          nodePort: 32444
          port: 32444
        extraEnv:
          - name: PEERPORT
            value: "32444"
          - name: TZ
            value: America/Vancouver
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        extraVolumes:
          - name: tv-library
            persistentVolumeClaim:
              claimName: {{ .Values.media.libraries.tv.claimName }}
        extraVolumeMounts:
          - name: tv-library
            mountPath: /downloads
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values: [ transmission ]
                topologyKey: kubernetes.io/hostname

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.media.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - kind: Secret
      name: transmission-tv-web-secret
      jsonPointers:
        - /data/USER
        - /data/PASS
