apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media
  source:
    repoURL: {{ .Values.repository.url }}
    targetRevision: HEAD
    path: transmission

    helm:
      valuesObject:
        {{- toYaml .Values.transmission.valuesObject | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.transmission.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - kind: Secret
      name: transmission-web-secret
      jsonPointers:
        - /data/USER
        - /data/PASS
