apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
  namespace: operators
spec:
  channel: stable
  name: external-secrets-operator
  source: operatorhubio-catalog
  sourceNamespace: {{ .Values.olm.namespace }}
