apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-forest-rcon-password
spec:
  encryptedData:
    rcon-password: AgALdJ0LcogQ95W13KpS2SIaUx++1mkTGZm/2Y2qb4sxCII2QqHb8mX1SsrdPln504/sntvKD/a5VwEP9cM6wjoxKCllNaPi2usc23ZalNxThk7Ij+exyRO2ACh/SgDMKAhIXxN+t5rbCjQvbL6o2dEAjX3atFpT8FUfe3KgJyvhsF7Xm1EP3hrhth0fNihf3K5SO1oMS94SGk8AOQlyFjcdKmV0DYF0V1WTOWFiuTTZoizFYf+Ismp2VQppUve9nQ3fddwyEBftTb+iATFlrKzaekdy0Hyoi+kGAV3j31ktXb0Wm6q/Z7P3VZm1tp4d81OSj8B4GR4tvm5O+5Sfxl0x6OeuBZBHjnk0EVrcYdXgf5VI6Xdy1j5Hmw/5i3XJKBJrMLLBD3bbGUJLzTZDDBRupme5/GXFsGsL+iRK8QpwvpDY45m5BNWO5W4VASjM1qo6wANuJZ9M9jtkjHEGZMoFb2GmipHeoVXGdMHa3Zoh9siRp4ACwmKCdyPjOu/dGNWcEUSj/R6AjhWw4I6IuoX7ufPLXAxMrI34x/OcqnbtmJDfeydKZMZdcfv7jXnGbrCIrIrgr5rOw2Pl4BZRTHa1OnNth40YDMnU1nZ9jk2TlvXRUXd19H/NApvKnAHCAljbxkM+PcRFkhs4uwtcT7/ERIKMWF4YOvIXxzyLOPEx5QvtPnSJXaGi3M9armyjIEF6i0yOkMJiZhSNiKw7DIFDwrwD0KhALM1CTai7oY0MMw==
