apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: media
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: 0.3.0
    chart: plex-media-server

    helm:
      valuesObject:
        image:
          registry: lscr.io
          repository: linuxserver/plex
          tag: latest
          pullPolicy: Always
        ingress:
          enabled: true
          ingressClassName: nginx
          url: plex.d3adb5.net
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
        extraEnv:
          # If redeploying, generate a new claim token through https://www.plex.tv/claim/
          PLEX_CLAIM: "claim-XCDywQgFEjsJF8rkMSSa"
          HOSTNAME: Plexgu
          PUID: 1000
          PGID: 1000
          VERSION: docker
          TZ: America/Vancouver
        extraVolumes:
          - name: movies-library
            persistentVolumeClaim:
              claimName: media-library-movies
          - name: tv-library
            persistentVolumeClaim:
              claimName: media-library-tv
        extraVolumeMounts:
          - name: tv-library
            mountPath: /media/tv
            subPath: library
          - name: movies-library
            mountPath: /media/movies
            subPath: library
        service:
          type: NodePort
          nodePort: 32400
        pms:
          storageClassName: longhorn-nvme
          configStorage: 2Gi
          resources:
            requests:
              cpu: 300m
              memory: 2Gi
            limits:
              cpu: 300m
              memory: 2Gi
        statefulSet:
          podAnnotations:
            linkerd.io/inject: enabled

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.plex.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
