apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.9.1
    chart: argo-cd

    helm:
      valuesObject:
        global:
          domain: argo.d3adb5.net
          podAnnotations:
            linkerd.io/inject: enabled

        redisSecretInit:
          podAnnotations:
            linkerd.io/inject: disabled

        configs:
          params:
            server.insecure: true
          cm:
            accounts.difford: apiKey
            oidc.config: |
              name: Keycloak
              issuer: https://id.d3adb5.net/realms/core
              clientID: argocd
              clientSecret: $oidc.keycloak.clientSecret
              requestedScopes: ["openid", "profile", "email", "groups"]
          rbac:
            policy.csv: |
              g, /Admin,   role:admin
              g, /Argo CD, role:readonly
              g, difford,  role:readonly

        controller:
          replicas: 1

        redis-ha:
          enabled: true
          podAnnotations:
            linkerd.io/inject: enabled
            config.linkerd.io/opaque-ports: "6379,26379"
          haproxy:
            annotations:
              linkerd.io/inject: enabled

        server:
          autoscaling:
            enabled: true
            minReplicas: 2
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              cert-manager.io/cluster-issuer: "letsencrypt"
            tls: true

        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 2

        applicationSet:
          replicas: 2

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
