identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIBjTCCATOgAwIBAgIQIvht8hmkwHraoV7BtVvwgjAKBggqhkjOPQQDAjAlMSMw
  IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNDA0MDMwMTIw
  NTJaFw0yOTA0MDIwMTIwNTJaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
  dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4EeQn8MUtU3UBWeW
  dg3YaBncGPGAzO/hDh2zZ/uHkH47O8Q3V7lhwPUYDBG5WDe0DIad6Mz/4VgArI1L
  0SI7BqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
  VR0OBBYEFKrK/huKsXPuF5Eoqo8Zy97yI9+WMAoGCCqGSM49BAMCA0gAMEUCIBCj
  JBT2hrqrkmgO1bXlTE6cnyvJw+/v/bcGuOSO90EyAiEA6QKMzMi5S1nybawDYTuC
  xmzLng6l/Y18scw8DdDS8iQ=
  -----END CERTIFICATE-----
identity:
  issuer:
    scheme: kubernetes.io/tls
