apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: storage
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.6.0
    chart: longhorn

    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClassReplicaCount: 1
          migratable: true

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.longhorn.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
