apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: storage
  source:
    repoURL: {{ .Values.repository.url }}
    targetRevision: HEAD
    path: longhorn

    helm:
      valuesObject:
        longhorn:
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClassReplicaCount: 1
            migratable: true
          ingress:
            enabled: true
            ingressClassName: {{ .Values.longhorn.ingress.ingressClassName }}
            host: {{ .Values.longhorn.ingress.host }}
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            tls: true

          defaultSettings:
            taintToleration: "purpose=storage:NoSchedule"

          longhornManager:
            tolerations:
              {{- toYaml .Values.longhorn.tolerations | nindent 14 }}
          longhornDriver:
            tolerations:
              {{- toYaml .Values.longhorn.tolerations | nindent 14 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.longhorn.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - kind: Secret
      name: longhorn-ui-secret
      jsonPointers:
        - /data/auth
        - /data/generatedPassword
