apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.6.0
    chart: longhorn

    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.longhorn.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
