apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Services backing cluster storage
  sourceRepos:
    - "*"
  destinations:
    - namespace: {{ .Values.longhorn.namespace }}
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: scheduling.k8s.io
      kind: PriorityClass
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: storage.k8s.io
      kind: StorageClass
