apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: HashiCorp Vault related services
  sourceRepos:
    - "*"
  destinations:
    - namespace: {{ .Values.vault.namespace }}
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
