apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: ingress
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    chart: ingress-nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.ingress.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
