apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ingress
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.2
    chart: ingress-nginx

    helm:
      valuesObject:
        controller:
          service:
            annotations:
              metallb.universe.tf/allow-shared-ip: {{ .Values.metallb.ipSharingKey }}
          podAnnotations:
            linkerd.io/inject: enabled

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.ingress.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
