apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: vault
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.27.0
    chart: vault

    helm:
      valuesObject:
        global:
          enabled: false
        server:
          annotations:
            linkerd.io/inject: enabled
          enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          standalone:
            enabled: true
          dataStorage:
            enabled: true
            storageClass: longhorn-nvme
            size: 3Gi
          affinity: |
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: {{ "{{ template \"vault.name\" . }}" }}
                        app.kubernetes.io/instance: {{ quote "{{ .Release.Name }}" }}
                        component: server
                    topologyKey: kubernetes.io/hostname
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
              - host: vault.d3adb5.net
            tls:
              - hosts: [ vault.d3adb5.net ]
                secretName: vault-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.vault.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
