apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc-jngs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minecraft
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 4.19.0
    chart: minecraft

    helm:
      valuesObject:
        podAnnotations:
          linkerd.io/inject: enabled
          config.linkerd.io/opaque-ports: "25565"
        workloadAsStatefulSet: true
        strategyType: RollingUpdate
        persistence:
          storageClass: longhorn-nvme
          dataDir:
            enabled: true
            Size: 10Gi
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 2500m
            memory: 2Gi
        minecraftServer:
          eula: true
          type: PAPER
          whitelist: d3adb5,pijung
          ops: d3adb5,pijung
          maxPlayers: 10
          allowNether: true
          announcePlayerAchievements: true
          spawnProtection: 0
          viewDistance: 12
          motd: "You are what you do, not what you say you'll do."
          icon: "http://0x0.st/Hhpt.png"
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - minecraft
                  topologyKey: kubernetes.io/hostname

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.minecraft.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
