apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc-router
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minecraft
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 1.2.5
    chart: mc-router

    helm:
      valuesObject:
        podAnnotations:
          linkerd.io/inject: enabled
          config.linkerd.io/opaque-ports: "25565"
        services:
          minecraft:
            type: LoadBalancer
            port: 25565
            annotations:
              metallb.universe.tf/allow-shared-ip: {{ .Values.metallb.ipSharingKey }}
        minecraftRouter:
          mappings:
            - externalHostname: wiggleton.picori.ca
              host: minecraft-wiggleton
              port: 25565
            - externalHostname: zuwi.picori.ca
              host: minecraft-zuwi
              port: 25565
            - externalHostname: minecraft.d3adb5.net
              host: minecraft-debson
              port: 25565
            - externalHostname: jungle.minecraft.d3adb5.net
              host: minecraft-jungle
              port: 25565
            - externalHostname: debson.minecraft.d3adb5.net
              host: minecraft-debson
              port: 25565
            - externalHostname: forest.minecraft.d3adb5.net
              host: minecraft-forest
              port: 25565
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 32Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.minecraft.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
