apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-wiggleton
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minecraft
  sources:
    - repoURL: {{ .Values.appOfApps.repoURL }}
      targetRevision: HEAD
      path: minecraft/wiggleton
      ref: appOfApps
    - repoURL: https://itzg.github.io/minecraft-server-charts
      targetRevision: 4.26.4
      chart: minecraft
      helm:
        valueFiles:
          - $appOfApps/minecraft/wiggleton/values/minecraft-4.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.minecraft.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
