apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global-operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  source:
    repoURL: {{ .Values.appOfApps.repoURL }}
    targetRevision: HEAD
    path: operators/global
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
