apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Argo CD operators, mainly managed through OLM
  sourceRepos:
    - {{ .Values.appOfApps.repoURL }}
    - "https://github.com/operator-framework/operator-lifecycle-manager"
  destinations:
    - namespace: operators
      server: https://kubernetes.default.svc
    - namespace: operator-lifecycle-manager
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
