apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: linkerd
  sources:
    - repoURL: {{ .Values.appOfApps.repoURL }}
      targetRevision: HEAD
      path: linkerd
      ref: extraResources

    - repoURL: https://helm.linkerd.io/stable
      targetRevision: 1.8.0
      chart: linkerd-crds

    - repoURL: https://helm.linkerd.io/stable
      targetRevision: 1.16.11
      chart: linkerd-control-plane
      helm:
        valueFiles:
          - $extraResources/linkerd/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      name:  linkerd-proxy-injector-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: ""
      kind: Secret
      name:  linkerd-sp-validator-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: ""
      kind: Secret
      name:  linkerd-policy-validator-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name:  linkerd-proxy-injector-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name:  linkerd-sp-validator-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name:  linkerd-policy-validator-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
