apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: linkerd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: A minimal service mesh for Kubernetes
  sourceRepos:
    - https://helm.linkerd.io/stable
    - {{ .Values.repository.url }}
  destinations:
    - namespace: linkerd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
