apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}-web-secret
type: Opaque
data:
  USER: {{ .Values.transmission.webUser | default (randAlpha 12) | b64enc | quote }}
  PASS: {{ randAlphaNum 24 | b64enc | quote }}
