apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if eq .Values.peerService.type "NodePort" }}
  name: {{ include "transmission.fullname" . }}-peer
  {{- else }}
  name: {{ include "transmission.fullname" . }}-peer-tcp
  {{- end }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.peerService.annotations | nindent 4 }}
spec:
  type: {{ .Values.peerService.type }}
  ports:
    - port: {{ .Values.peerService.port }}
      targetPort: peer-tcp
      protocol: TCP
      name: peer-tcp
      nodePort: {{ .Values.peerService.nodePort }}
    {{- if eq .Values.peerService.type "NodePort" }}
    - port: {{ .Values.peerService.port }}
      targetPort: peer-udp
      protocol: UDP
      name: peer-udp
      nodePort: {{ .Values.peerService.nodePort }}
    {{- end }}
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
{{- if ne .Values.peerService.type "NodePort" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-peer-udp
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.peerService.annotations | nindent 4 }}
spec:
  type: {{ .Values.peerService.type }}
  ports:
    - port: {{ .Values.peerService.port }}
      targetPort: peer-udp
      protocol: UDP
      name: peer-udp
      nodePort: {{ .Values.peerService.nodePort }}
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
{{- end }}
