apiVersion: v1
kind: Secret
metadata:
  name: longhorn-ui-secret
type: Opaque
data:
  {{- $generatedPassword := randAlphaNum 20 }}
  generatedPassword: {{ b64enc $generatedPassword | quote }}
  auth: {{ htpasswd .Values.ui.username $generatedPassword | b64enc | quote }}
