apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app-of-apps.fullname" . }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.appOfApps.repoURL }}
    targetRevision: HEAD
    path: app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
