apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app-of-apps.fullname" . }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repository.url }}
    targetRevision: HEAD
    path: app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd.namespace }}
