apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-peer-tcp
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.peerService.annotations | nindent 4 }}
spec:
  type: {{ .Values.peerService.type }}
  ports:
    - port: {{ .Values.peerService.port }}
      targetPort: peer-tcp
      protocol: TCP
      name: peer-tcp
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-peer-udp
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.peerService.annotations | nindent 4 }}
spec:
  type: {{ .Values.peerService.type }}
  ports:
    - port: {{ .Values.peerService.port }}
      targetPort: peer-udp
      protocol: UDP
      name: peer-udp
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
