apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
spec:
  channel: stable
  name: external-secrets-operator
  source: operatorhubio-catalog
  sourceNamespace: operator-lifecycle-manager
---
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: external-secrets-operator
spec:
  podAnnotations:
    linkerd.io/inject: enabled
