repository:
  url: https://github.com/d3adb5/argo-applications

olm:
  namespace: operator-lifecycle-manager

keycloak:
  namespace: keycloak

argocd:
  namespace: argo-cd

metallb:
  namespace: metallb
  ipSharingKey: &metallb-sharing-key metallb-single-ip

ingress:
  namespace: ingress

certManager:
  namespace: cert-manager

longhorn:
  namespace: longhorn
  defaultSettings:
    taintToleration: "purpose=storage:NoSchedule"
  ingress:
    host: longhorn.d3adb5.net
    ingressClassName: nginx
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  tolerations:
    - key: purpose
      operator: Equal
      value: storage
      effect: NoSchedule

prometheus:
  namespace: prometheus

minecraft:
  namespace: minecraft

vault:
  namespace: vault

plex:
  namespace: media

transmission:
  namespace: media

sonarr:
  namespace: media
  valuesObject:

radarr:
  namespace: media

overseerr:
  namespace: media

prowlarr:
  namespace: media
  valuesObject:
    replicaCount: 1
    image:
      repository: lscr.io/linuxserver/prowlarr
      tag: latest
      pullPolicy: Always
    persistence:
      config:
        storageClass: longhorn-nvme
    service:
      port: 9696
    ingress:
      enabled: true
      host: prowlarr.d3adb5.net
      className: nginx
      tls:
        enabled: true
        secretName: prowlarr-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    extraEnv:
      - name: TZ
        value: America/Vancouver
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
