ui:
  username: admin

longhorn:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: longhorn-ui-secret
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required "
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m

extraStorageClasses:
  - name: longhorn-nvme
    dataLocality: best-effort
    numberOfReplicas: 2
    diskSelector: nvme
  - name: longhorn-hdd
    dataLocality: disabled
    diskSelector: hdd
  - name: longhorn-large
    dataLocality: disabled
    diskSelector: large
