apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-zuwi-rcon-password
spec:
  encryptedData:
    rcon-password: AgCKQNUvFBvfR8HlKVRheMFicZ34+RlO/Co3PVOZoPDfEpuoZ23ycy/JWXO2YoLjgA4a1A9V2zBYH8Uy4qCJZeftvHnYlALqbR55oXK5aXceC9cbzSb1XppTduQBSoe+1zxS4VJz0CWEpNJhEaSy9L4XVKnbmPrFJ1onW9GgRATMvWK6Q1H30qMIRLq41dfSXobPcf799wF5jC7hFK2RDUJ38EV/sWrukjzLR3NblE3XmI3IosqZyY79VSMePaSZMsKL8kU+ipvgrVWGuiYuj5TS2tBACJtIRbATlBwGP/Ikfc1cQ6CZMVB6M2qbnP1T0on3JPyQ2csrfLw5mvU2EY20iOEaRRlpUeVG0z8eTA2gUAo7M7lm6puhTCuy/iKaFJ1guJUKHaDc/OaHmppfiyZyUYgfp82HEHQ9phh2PgQHwqv3MZPJN+NU8IGoQ001mSrxhzODIMNWfi4tmHGwpPKV3NGS/kqgGL+4DsaYJaa9Yz77wDPmNoQwfS3kbM7gV/DcocFLzNpBhPssHr0mtVjfijgWG3EgUKUgnvbjBAFvkp7fZgj4KnC3b/95troM1OTWMirwKp9Efa3wfFZvBR4GxcG02w1aWb8Q2K9uUhizO58k/SQ7endgh4pYFDrfS33605/awVLTSlHtqbLkfPrdNOAUGCri75w/ZIwVTXinR34IllRvbZz72ZHfqzLBXX1NcL0DipHV0qSoMzrWaNj3PVyxGpz/IQaTbZii6dQUYAwhZRkZsPjyOzHRWag=
